PORTFOLIO_CCY = 'GBP'
STARTING_CAPITAL = 20000

AVG_FORECAST = 10
MIN_FORECAST = -20
MAX_FORECAST = 20

MAX_DIVERSIFICATION_MULTIPLIER = 2.5

VOL_TARGET = 20  # TODO - revisit this value
VOL_SPAN = 25

TRADING_DAYS_PER_YEAR = 252

MAX_FFILL = 5
